export const SYLLABUS_LIST_REQUEST = 'SYLLABUS_LIST_REQUEST'
export const SYLLABUS_LIST_SUCCESS = 'SYLLABUS_LIST_SUCCESS'
export const SYLLABUS_LIST_FAIL = 'SYLLABUS_LIST_FAIL'

export const SYLLABUS_PROF_LIST_REQUEST = 'SYLLABUS_PROF_LIST_REQUEST'
export const SYLLABUS_PROF_LIST_SUCCESS = 'SYLLABUS_PROF_LIST_SUCCESS'
export const SYLLABUS_PROF_LIST_FAIL = 'SYLLABUS_PROF_LIST_FAIL'

export const SYLLABUS_DETAILS_REQUEST = 'SYLLABUS_DETAILS_REQUEST'
export const SYLLABUS_DETAILS_SUCCESS = 'SYLLABUS_DETAILS_SUCCESS'
export const SYLLABUS_DETAILS_FAIL = 'SYLLABUS_DETAILS_FAIL'

export const SYLLABUS_PROF_DETAILS_REQUEST = 'SYLLABUS_PROF_DETAILS_REQUEST'
export const SYLLABUS_PROF_DETAILS_SUCCESS = 'SYLLABUS_PROF_DETAILS_SUCCESS'
export const SYLLABUS_PROF_DETAILS_FAIL = 'SYLLABUS_PROF_DETAILS_FAIL'

export const SYLLABUS_CREATE_REQUEST = 'SYLLABUS_CREATE_REQUEST'
export const SYLLABUS_CREATE_SUCCESS = 'SYLLABUS_CREATE_SUCCESS'
export const SYLLABUS_CREATE_RESET = 'SYLLABUS_CREATE_RESET'
export const SYLLABUS_CREATE_FAIL = 'SYLLABUS_CREATE_FAIL'

export const SYLLABUS_CREATE_VIDEO_REQUEST = 'SYLLABUS_CREATE_VIDEO_REQUEST'
export const SYLLABUS_CREATE_VIDEO_SUCCESS = 'SYLLABUS_CREATE_VIDEO_SUCCESS'
export const SYLLABUS_CREATE_VIDEO_RESET = 'SYLLABUS_CREATE_VIDEO_RESET'
export const SYLLABUS_CREATE_VIDEO_FAIL = 'SYLLABUS_CREATE_VIDEO_FAIL'